apiVersion: v1
kind: Namespace
metadata:
  name: blog-be
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: blog-be
  name: blog-be-sa
  annotations:
    iam.gke.io/gcp-service-account: gcp-blog-be@gcp-automated-blog-test.iam.gserviceaccount.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: credentials-sh
  namespace: blog-be
data:
  credentials.sh: |-
    #!/bin/bash
    yum install jq -y &> /dev/null
    jwt_token=$(curl -sH "Metadata-Flavor: Google" "http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=accounts.google.com&format=full&licenses=FALSE")
    credentials=$(aws sts assume-role-with-web-identity --profile credentials_script --role-arn $AWS_ROLE_ARN --role-session-name accounts.google.com --web-identity-token $jwt_token | jq '.Credentials' | jq '.Version=1')
    echo $credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  namespace: blog-be
data:
  config: |-
    [default]
    credential_process = /root/credentials.sh
---
apiVersion: v1
kind: Pod
metadata:
  name: blog-be
  namespace: blog-be
spec:
  serviceAccount: blog-be-sa
  containers:
    - name: awscli
      image: amazon/aws-cli:latest
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      volumeMounts:
        - name: credentials-sh
          mountPath: /root
        - name: aws-config
          mountPath: /root/.aws
      env:
        - name: GCP_OAUTH_AUD
          value: "108840315781302076417"
        - name: AWS_ROLE_ARN
          value: "arn:aws:iam::460446231952:role/autoblog-test-gcp-101473088463169348979"
  volumes:
    - name: credentials-sh
      configMap:
        name: credentials-sh
        defaultMode: 0777
        items:
          - key: credentials.sh
            path: credentials.sh
    - name: aws-config
      configMap:
        name: aws-config
        items:
          - key: config
            path: config
