region: europe-west4
description: Sample description
ip_cidr_range: 10.0.1.0/24
# enable_private_access: true  # defaults to true
# iam:
secondary_ip_ranges: # map of secondary ip ranges
  pods: 172.16.0.0/21
  services: 172.16.8.0/27
flow_logs_config:
  aggregation_interval: "INTERVAL_5_SEC"
  flow_sampling: 0.5
  metadata: "INCLUDE_ALL_METADATA"
