ingress:
  allow-iap-to-bastion:
    description: Allow ingress SSH from IAP to Bastion Host
    source_ranges:
      - 35.235.240.0/20
    use_service_accounts: true
    sources:
      - tf-vm-auto-blog-bastion-vm@gcp-automated-blog-prod.iam.gserviceaccount.com
    rules:
      - protocol: tcp
        ports:
          - 22
